### ISSUE TITLE
Add a command to see the next scheduled notification

### ISSUE THREAD

**Issue by DelightedCat** [DelightedCat/WaterBot#4]
In order to make the notification system more transparent and easier to debug, we'd need a command that presents us with the next timestamp where we have a notification schedules. The command could look like the following:
```
wb!config next
```
This would return an embed showing the next timestamp. Please note that this time should be displayed in the user's timezone and not in UTC. See [this](https://github.com/DelightedCat/WaterBot/commit/dc337265253219e8ac2c9baa1ea74cd6b6389cae) commit to see how I solved this using the user's configuration.

**Comment by JustAeris** [comment]
I'll work on this

**Comment by JustAeris** [comment]
Done, check #7!

**Comment by DelightedCat** [comment]
I'm gonna be keeping this open until #7 is ready to be merged.
